# config.yaml

# Current node ID (can be overridden by command line flag)
id: 0

# Cluster nodes configuration
nodes:
  - id: 0
    raft_addr: "127.0.0.1:25000"
    kv_addr:   "127.0.0.1:26000"
    im_http_addr: "127.0.0.1:28080"
    im_grpc_addr: "127.0.0.1:27000"

  - id: 1
    raft_addr: "127.0.0.1:25001"
    kv_addr:   "127.0.0.1:26001"
    im_http_addr: "127.0.0.1:28081"
    im_grpc_addr: "127.0.0.1:27001"

  - id: 2
    raft_addr: "127.0.0.1:25002"
    kv_addr:   "127.0.0.1:26002"
    im_http_addr: "127.0.0.1:28082"
    im_grpc_addr: "127.0.0.1:27002"